version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
     steps:
      - checkout
      -run:
          name: Update npm
          command" 'sudo npm install -g npm@latest'
      - run: echo "A first Hello to Bob Thedog"
